<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAXJ4fIA\ProductsAPIDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAXJ4fIA/ProductsAPIDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAXJ4fIA.legacy');

    return;
}

if (!\class_exists(ProductsAPIDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAXJ4fIA\ProductsAPIDevDebugProjectContainer::class, ProductsAPIDevDebugProjectContainer::class, false);
}

return new \ContainerAXJ4fIA\ProductsAPIDevDebugProjectContainer(array(
    'container.build_hash' => 'AXJ4fIA',
    'container.build_id' => '4a327f5b',
    'container.build_time' => 1538559691,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerAXJ4fIA');
