<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSLdrxlu\ProductsDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSLdrxlu/ProductsDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSLdrxlu.legacy');

    return;
}

if (!\class_exists(ProductsDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSLdrxlu\ProductsDevDebugProjectContainer::class, ProductsDevDebugProjectContainer::class, false);
}

return new \ContainerSLdrxlu\ProductsDevDebugProjectContainer(array(
    'container.build_hash' => 'SLdrxlu',
    'container.build_id' => '0d1d7aec',
    'container.build_time' => 1537947601,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSLdrxlu');
