<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNx40u1N\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNx40u1N/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNx40u1N.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNx40u1N\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerNx40u1N\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Nx40u1N',
    'container.build_id' => '54720509',
    'container.build_time' => 1537257523,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerNx40u1N');
